from __future__ import annotations

from dataclasses import dataclass


RAW_PORTAL_SCHEMA = "raw_pe_portal"
RAW_MASTER_SCHEMA = "raw_pe_master"
BRONZE_SCHEMA = "bronze_pe"
SILVER_SCHEMA = "silver_pe"
GOLD_GLOBAL_SCHEMA = "gold_pe_global"

RAW_AUDIT_COLUMNS = [
    "_ingestion_run_id",
    "_ingested_at",
    "_source_system",
    "_source_table",
    "_extract_started_at",
    "_extract_ended_at",
    "_record_hash",
    "_dq_status",
    "_dq_errors",
]

SILVER_TABLES = [
    "dim_doctor",
    "dim_field_rep",
    "dim_campaign",
    "dim_video",
    "dim_bundle",
    "bridge_bundle_video",
    "bridge_campaign_content",
    "map_campaign_doctor_to_doctor",
    "fact_campaign_enrollment",
    "bridge_campaign_doctor_base",
    "fact_share_activity",
    "fact_share_playback_event",
    "fact_share_funnel_first_seen",
    "fact_video_view",
    "recon_doctor_share_summary",
]


@dataclass(frozen=True)
class SourceTableSpec:
    source_table: str
    raw_table: str
    bronze_table: str
    columns: list[str]
    key_columns: list[str]
    watermark_field: str | None = None
    lookback_days: int = 30


PORTAL_TABLE_SPECS: dict[str, SourceTableSpec] = {
    "sharing_doctorsharesummary": SourceTableSpec(
        source_table="sharing_doctorsharesummary",
        raw_table="sharing_doctorsharesummary_raw",
        bronze_table="sharing_doctorsharesummary",
        columns=[
            "id",
            "doctor_id",
            "doctor_name_snapshot",
            "clinic_name_snapshot",
            "total_shares",
            "last_shared_at",
            "created_at",
            "updated_at",
        ],
        key_columns=["id"],
        watermark_field="updated_at",
    ),
    "sharing_shareactivity": SourceTableSpec(
        source_table="sharing_shareactivity",
        raw_table="sharing_shareactivity_raw",
        bronze_table="sharing_shareactivity",
        columns=[
            "id",
            "public_id",
            "doctor_summary_id",
            "doctor_id",
            "doctor_name_snapshot",
            "clinic_name_snapshot",
            "share_channel",
            "shared_by_role",
            "shared_item_type",
            "shared_item_code",
            "shared_item_name",
            "language_code",
            "recipient_reference",
            "recipient_reference_version",
            "shared_at",
        ],
        key_columns=["public_id"],
        watermark_field="shared_at",
    ),
    "sharing_shareplaybackevent": SourceTableSpec(
        source_table="sharing_shareplaybackevent",
        raw_table="sharing_shareplaybackevent_raw",
        bronze_table="sharing_shareplaybackevent",
        columns=[
            "id",
            "share_id",
            "share_public_id",
            "doctor_summary_id",
            "doctor_id",
            "page_item_type",
            "event_type",
            "video_code",
            "video_name",
            "milestone_percent",
            "occurred_at",
        ],
        key_columns=["id"],
        watermark_field="occurred_at",
    ),
    "publisher_campaign": SourceTableSpec(
        source_table="publisher_campaign",
        raw_table="publisher_campaign_raw",
        bronze_table="publisher_campaign",
        columns=[
            "campaign_id",
            "new_video_cluster_name",
            "selection_json",
            "doctors_supported",
            "banner_small",
            "banner_large",
            "banner_target_url",
            "start_date",
            "end_date",
            "video_cluster_id",
            "publisher_sub",
            "publisher_username",
            "publisher_roles",
            "email_registration",
            "wa_addition",
            "created_at",
            "updated_at",
        ],
        key_columns=["campaign_id"],
        watermark_field="updated_at",
    ),
    "catalog_therapyarea": SourceTableSpec(
        source_table="catalog_therapyarea",
        raw_table="catalog_therapyarea_raw",
        bronze_table="catalog_therapyarea",
        columns=["id", "code", "display_name", "description", "sort_order", "is_active"],
        key_columns=["id"],
    ),
    "catalog_triggercluster": SourceTableSpec(
        source_table="catalog_triggercluster",
        raw_table="catalog_triggercluster_raw",
        bronze_table="catalog_triggercluster",
        columns=["id", "code", "display_name", "description", "language_code", "is_active", "sort_order"],
        key_columns=["id"],
    ),
    "catalog_trigger": SourceTableSpec(
        source_table="catalog_trigger",
        raw_table="catalog_trigger_raw",
        bronze_table="catalog_trigger",
        columns=[
            "id",
            "code",
            "display_name",
            "doctor_trigger_label",
            "subtopic_title",
            "navigation_pathways",
            "search_keywords",
            "cluster_id",
            "primary_therapy_id",
            "is_active",
            "sort_order",
        ],
        key_columns=["id"],
    ),
    "catalog_video": SourceTableSpec(
        source_table="catalog_video",
        raw_table="catalog_video_raw",
        bronze_table="catalog_video",
        columns=[
            "id",
            "code",
            "description",
            "thumbnail_url",
            "primary_therapy_id",
            "primary_trigger_id",
            "sort_order",
            "is_published",
            "search_keywords",
            "is_active",
            "created_at",
            "updated_at",
        ],
        key_columns=["id"],
        watermark_field="updated_at",
    ),
    "catalog_videolanguage": SourceTableSpec(
        source_table="catalog_videolanguage",
        raw_table="catalog_videolanguage_raw",
        bronze_table="catalog_videolanguage",
        columns=["id", "video_id", "language_code", "title", "youtube_url"],
        key_columns=["id"],
    ),
    "catalog_videocluster": SourceTableSpec(
        source_table="catalog_videocluster",
        raw_table="catalog_videocluster_raw",
        bronze_table="catalog_videocluster",
        columns=[
            "id",
            "code",
            "display_name",
            "description",
            "trigger_id",
            "sort_order",
            "is_published",
            "search_keywords",
            "is_active",
            "created_at",
            "updated_at",
        ],
        key_columns=["id"],
        watermark_field="updated_at",
    ),
    "catalog_videoclusterlanguage": SourceTableSpec(
        source_table="catalog_videoclusterlanguage",
        raw_table="catalog_videoclusterlanguage_raw",
        bronze_table="catalog_videoclusterlanguage",
        columns=["id", "video_cluster_id", "language_code", "name"],
        key_columns=["id"],
    ),
    "catalog_videoclustervideo": SourceTableSpec(
        source_table="catalog_videoclustervideo",
        raw_table="catalog_videoclustervideo_raw",
        bronze_table="catalog_videoclustervideo",
        columns=["id", "video_cluster_id", "video_id", "sort_order"],
        key_columns=["id"],
    ),
    "catalog_videotriggermap": SourceTableSpec(
        source_table="catalog_videotriggermap",
        raw_table="catalog_videotriggermap_raw",
        bronze_table="catalog_videotriggermap",
        columns=["id", "video_id", "trigger_id", "is_primary", "sort_order"],
        key_columns=["id"],
    ),
}

MASTER_TABLE_SPECS: dict[str, SourceTableSpec] = {
    "redflags_doctor": SourceTableSpec(
        source_table="redflags_doctor",
        raw_table="redflags_doctor_raw",
        bronze_table="redflags_doctor",
        columns=[
            "doctor_id",
            "first_name",
            "last_name",
            "email",
            "whatsapp_no",
            "clinic_name",
            "clinic_phone",
            "created_at",
            "clinic_address",
            "postal_code",
            "state",
            "district",
            "partner_id",
            "field_rep_id",
            "recruited_via",
        ],
        key_columns=["doctor_id"],
        watermark_field="created_at",
    ),
    "campaign_doctor": SourceTableSpec(
        source_table="campaign_doctor",
        raw_table="campaign_doctor_raw",
        bronze_table="campaign_doctor",
        columns=["id", "doctor_id", "full_name", "email", "phone", "city", "state", "created_at"],
        key_columns=["id"],
        watermark_field="created_at",
    ),
    "campaign_doctorcampaignenrollment": SourceTableSpec(
        source_table="campaign_doctorcampaignenrollment",
        raw_table="campaign_doctorcampaignenrollment_raw",
        bronze_table="campaign_doctorcampaignenrollment",
        columns=[
            "campaign_id",
            "doctor_id",
            "registered_at",
            "created_at",
            "updated_at",
            "registered_by_id",
            "whitelabel_enabled",
            "whitelabel_subdomain",
        ],
        key_columns=["campaign_id", "doctor_id"],
        watermark_field="registered_at",
    ),
    "campaign_campaign": SourceTableSpec(
        source_table="campaign_campaign",
        raw_table="campaign_campaign_raw",
        bronze_table="campaign_campaign",
        columns=[
            "id",
            "name",
            "brand_id",
            "start_date",
            "end_date",
            "created_at",
            "system_pe",
            "num_doctors_supported",
            "add_to_campaign_message",
            "register_message",
            "banner_small_url",
            "banner_large_url",
            "banner_target_url",
        ],
        key_columns=["id"],
        watermark_field="created_at",
    ),
    "campaign_brand": SourceTableSpec(
        source_table="campaign_brand",
        raw_table="campaign_brand_raw",
        bronze_table="campaign_brand",
        columns=["id", "name"],
        key_columns=["id"],
    ),
    "campaign_fieldrep": SourceTableSpec(
        source_table="campaign_fieldrep",
        raw_table="campaign_fieldrep_raw",
        bronze_table="campaign_fieldrep",
        columns=[
            "id",
            "full_name",
            "phone_number",
            "brand_supplied_field_rep_id",
            "is_active",
            "state",
            "created_at",
            "updated_at",
        ],
        key_columns=["id"],
        watermark_field="updated_at",
    ),
    "campaign_campaignfieldrep": SourceTableSpec(
        source_table="campaign_campaignfieldrep",
        raw_table="campaign_campaignfieldrep_raw",
        bronze_table="campaign_campaignfieldrep",
        columns=["id", "campaign_id", "field_rep_id"],
        key_columns=["id"],
    ),
}
