from __future__ import annotations

from dataclasses import dataclass


RAW_PORTAL_SCHEMA = "raw_pe_portal"
RAW_MASTER_SCHEMA = "raw_pe_master"
BRONZE_SCHEMA = "bronze_pe"
SILVER_SCHEMA = "silver_pe"
GOLD_GLOBAL_SCHEMA = "gold_pe_global"

RAW_AUDIT_COLUMNS = [
    "_ingestion_run_id",
    "_ingested_at",
    "_source_system",
    "_source_table",
    "_extract_started_at",
    "_extract_ended_at",
    "_record_hash",
    "_source_payload_hash",
    "_dq_status",
    "_dq_errors",
]

SILVER_TABLES = [
    "dim_doctor",
    "dim_field_rep",
    "dim_campaign",
    "dim_video",
    "dim_bundle",
    "bridge_bundle_video",
    "bridge_campaign_content",
    "map_campaign_doctor_to_doctor",
    "fact_campaign_enrollment",
    "bridge_campaign_doctor_base",
    "fact_share_activity",
    "fact_share_playback_event",
    "fact_share_banner_click",
    "fact_share_funnel_first_seen",
    "fact_video_view",
    "recon_doctor_share_summary",
]


@dataclass(frozen=True)
class SourceTableSpec:
    source_table: str
    raw_table: str
    bronze_table: str
    columns: list[str]
    key_columns: list[str]
    watermark_field: str | None = None
    lookback_days: int = 30
    source_filters: dict[str, str] | None = None
    fallback_source_table: str | None = None
    use_current_snapshot: bool = False
    force_fallback_when_primary_empty: bool = False


PORTAL_TABLE_SPECS: dict[str, SourceTableSpec] = {
    "sharing_doctorsharesummary": SourceTableSpec(
        source_table="pe_doctor_share_summary_v2",
        raw_table="sharing_doctorsharesummary_raw",
        bronze_table="sharing_doctorsharesummary",
        columns=[
            "id",
            "doctor_id",
            "doctor_name_snapshot",
            "clinic_name_snapshot",
            "total_shares",
            "last_shared_at",
            "created_at",
            "updated_at",
        ],
        key_columns=["id"],
        watermark_field="updated_at",
        fallback_source_table="sharing_doctorsharesummary",
    ),
    "sharing_shareactivity": SourceTableSpec(
        source_table="pe_share_event_v2",
        raw_table="sharing_shareactivity_raw",
        bronze_table="sharing_shareactivity",
        columns=[
            "id",
            "share_event_uuid",
            "public_id",
            "doctor_summary_id",
            "doctor_id",
            "doctor_name_snapshot",
            "clinic_name_snapshot",
            "share_channel",
            "shared_by_role",
            "shared_item_type",
            "shared_item_code",
            "shared_item_name",
            "language_code",
            "recipient_reference",
            "recipient_reference_version",
            "shared_at",
            "campaign_uuid",
            "pe_campaign_uuid",
        ],
        key_columns=["public_id"],
        watermark_field="shared_at",
        fallback_source_table="sharing_shareactivity",
    ),
    "sharing_shareplaybackevent": SourceTableSpec(
        source_table="pe_playback_event_v2",
        raw_table="sharing_shareplaybackevent_raw",
        bronze_table="sharing_shareplaybackevent",
        columns=[
            "id",
            "share_id",
            "share_public_id",
            "doctor_summary_id",
            "doctor_id",
            "page_item_type",
            "event_type",
            "video_code",
            "video_name",
            "milestone_percent",
            "occurred_at",
            "campaign_uuid",
            "share_event_uuid",
        ],
        key_columns=["id"],
        watermark_field="occurred_at",
        fallback_source_table="sharing_shareplaybackevent",
    ),
    "sharing_sharebannerclickevent": SourceTableSpec(
        source_table="pe_banner_click_event_v2",
        raw_table="sharing_sharebannerclickevent_raw",
        bronze_table="sharing_sharebannerclickevent",
        columns=[
            "id",
            "page_type",
            "banner_id",
            "banner_name",
            "banner_target_url",
            "clicked_at",
            "doctor_id",
            "doctor_summary_id",
            "campaign_uuid",
            "source_banner_click_id",
        ],
        key_columns=["id"],
        watermark_field="clicked_at",
        fallback_source_table="sharing_sharebannerclickevent",
    ),
    "publisher_campaign": SourceTableSpec(
        source_table="pe_campaign_v2",
        raw_table="publisher_campaign_raw",
        bronze_table="publisher_campaign",
        columns=[
            "campaign_id",
            "new_video_cluster_name",
            "selection_json",
            "doctors_supported",
            "banner_small",
            "banner_large",
            "banner_target_url",
            "start_date",
            "end_date",
            "video_cluster_id",
            "publisher_sub",
            "publisher_username",
            "publisher_roles",
            "email_registration",
            "wa_addition",
            "created_at",
            "updated_at",
            "campaign_uuid",
            "pe_campaign_uuid",
            "pe_campaign_id_normalized",
            "master_campaign_id_normalized",
        ],
        key_columns=["campaign_id"],
        watermark_field="updated_at",
        fallback_source_table="publisher_campaign",
        force_fallback_when_primary_empty=True,
    ),
    "catalog_therapyarea": SourceTableSpec(
        source_table="pe_content_item_v2",
        raw_table="catalog_therapyarea_raw",
        bronze_table="catalog_therapyarea",
        columns=["id", "code", "display_name", "description", "sort_order", "is_active", "content_type"],
        key_columns=["id"],
        source_filters={"content_type": "therapy_area"},
        fallback_source_table="catalog_therapyarea",
    ),
    "catalog_triggercluster": SourceTableSpec(
        source_table="pe_content_item_v2",
        raw_table="catalog_triggercluster_raw",
        bronze_table="catalog_triggercluster",
        columns=["id", "code", "display_name", "description", "language_code", "is_active", "sort_order", "content_type"],
        key_columns=["id"],
        source_filters={"content_type": "trigger_cluster"},
        fallback_source_table="catalog_triggercluster",
    ),
    "catalog_trigger": SourceTableSpec(
        source_table="pe_content_item_v2",
        raw_table="catalog_trigger_raw",
        bronze_table="catalog_trigger",
        columns=[
            "id",
            "code",
            "display_name",
            "doctor_trigger_label",
            "subtopic_title",
            "navigation_pathways",
            "search_keywords",
            "cluster_id",
            "primary_therapy_id",
            "is_active",
            "sort_order",
            "content_type",
        ],
        key_columns=["id"],
        source_filters={"content_type": "trigger"},
        fallback_source_table="catalog_trigger",
    ),
    "catalog_video": SourceTableSpec(
        source_table="pe_content_item_v2",
        raw_table="catalog_video_raw",
        bronze_table="catalog_video",
        columns=[
            "id",
            "code",
            "description",
            "thumbnail_url",
            "primary_therapy_id",
            "primary_trigger_id",
            "sort_order",
            "is_published",
            "search_keywords",
            "is_active",
            "created_at",
            "updated_at",
            "content_type",
        ],
        key_columns=["id"],
        watermark_field="updated_at",
        source_filters={"content_type": "video"},
        fallback_source_table="catalog_video",
    ),
    "catalog_videolanguage": SourceTableSpec(
        source_table="pe_content_item_v2",
        raw_table="catalog_videolanguage_raw",
        bronze_table="catalog_videolanguage",
        columns=["id", "video_id", "language_code", "title", "youtube_url", "content_type"],
        key_columns=["id"],
        source_filters={"content_type": "video_language"},
        fallback_source_table="catalog_videolanguage",
    ),
    "catalog_videocluster": SourceTableSpec(
        source_table="pe_content_item_v2",
        raw_table="catalog_videocluster_raw",
        bronze_table="catalog_videocluster",
        columns=[
            "id",
            "code",
            "display_name",
            "description",
            "trigger_id",
            "sort_order",
            "is_published",
            "search_keywords",
            "is_active",
            "created_at",
            "updated_at",
            "content_type",
        ],
        key_columns=["id"],
        watermark_field="updated_at",
        source_filters={"content_type": "video_cluster"},
        fallback_source_table="catalog_videocluster",
    ),
    "catalog_videoclusterlanguage": SourceTableSpec(
        source_table="pe_content_item_v2",
        raw_table="catalog_videoclusterlanguage_raw",
        bronze_table="catalog_videoclusterlanguage",
        columns=["id", "video_cluster_id", "language_code", "name", "content_type"],
        key_columns=["id"],
        source_filters={"content_type": "cluster_language"},
        fallback_source_table="catalog_videoclusterlanguage",
    ),
    "catalog_videoclustervideo": SourceTableSpec(
        source_table="pe_content_item_v2",
        raw_table="catalog_videoclustervideo_raw",
        bronze_table="catalog_videoclustervideo",
        columns=["id", "video_cluster_id", "video_id", "sort_order", "content_type"],
        key_columns=["id"],
        source_filters={"content_type": "video_cluster_video"},
        fallback_source_table="catalog_videoclustervideo",
    ),
    "catalog_videotriggermap": SourceTableSpec(
        source_table="pe_content_item_v2",
        raw_table="catalog_videotriggermap_raw",
        bronze_table="catalog_videotriggermap",
        columns=["id", "video_id", "trigger_id", "is_primary", "sort_order", "content_type"],
        key_columns=["id"],
        source_filters={"content_type": "video_trigger_map"},
        fallback_source_table="catalog_videotriggermap",
    ),
    "pe_rep_assignment_credit": SourceTableSpec(
        source_table="pe_rep_assignment_credit_v2",
        raw_table="pe_rep_assignment_credit_raw",
        bronze_table="pe_rep_assignment_credit",
        columns=[
            "rep_assignment_credit_uuid",
            "campaign_uuid",
            "doctor_uuid",
            "field_rep_uuid",
            "credit_type",
            "credit_source_table",
            "credit_source_pk",
            "credit_effective_from",
            "credit_effective_to",
        ],
        key_columns=["rep_assignment_credit_uuid"],
        watermark_field="credit_effective_from",
    ),
}

MASTER_TABLE_SPECS: dict[str, SourceTableSpec] = {
    "redflags_doctor": SourceTableSpec(
        source_table="redflags_doctor",
        raw_table="redflags_doctor_raw",
        bronze_table="redflags_doctor",
        columns=[
            "doctor_id",
            "first_name",
            "last_name",
            "email",
            "whatsapp_no",
            "clinic_name",
            "clinic_phone",
            "created_at",
            "clinic_address",
            "postal_code",
            "state",
            "district",
            "partner_id",
            "field_rep_id",
            "recruited_via",
        ],
        key_columns=["doctor_id"],
        watermark_field="created_at",
    ),
    "campaign_doctor": SourceTableSpec(
        source_table="doctor_v2",
        raw_table="campaign_doctor_raw",
        bronze_table="campaign_doctor",
        columns=["doctor_uuid", "id", "doctor_id", "full_name", "email", "phone", "city", "state", "created_at"],
        key_columns=["id"],
        watermark_field="created_at",
    ),
    "campaign_doctorcampaignenrollment": SourceTableSpec(
        source_table="doctor_campaign_enrollment_v2",
        raw_table="campaign_doctorcampaignenrollment_raw",
        bronze_table="campaign_doctorcampaignenrollment",
        columns=[
            "doctor_campaign_enrollment_uuid",
            "campaign_id",
            "doctor_id",
            "campaign_uuid",
            "doctor_uuid",
            "registered_by_field_rep_uuid",
            "registered_at",
            "created_at",
            "updated_at",
            "registered_by_id",
            "whitelabel_enabled",
            "whitelabel_subdomain",
        ],
        key_columns=["campaign_id", "doctor_id"],
        watermark_field="registered_at",
    ),
    "campaign_campaign": SourceTableSpec(
        source_table="campaign_v2",
        raw_table="campaign_campaign_raw",
        bronze_table="campaign_campaign",
        columns=[
            "campaign_uuid",
            "id",
            "name",
            "brand_id",
            "start_date",
            "end_date",
            "created_at",
            "system_pe",
            "num_doctors_supported",
            "add_to_campaign_message",
            "register_message",
            "banner_small_url",
            "banner_large_url",
            "banner_target_url",
        ],
        key_columns=["id"],
        watermark_field="created_at",
    ),
    "campaign_brand": SourceTableSpec(
        source_table="brand_v2",
        raw_table="campaign_brand_raw",
        bronze_table="campaign_brand",
        columns=["brand_uuid", "id", "name"],
        key_columns=["id"],
    ),
    "campaign_fieldrep": SourceTableSpec(
        source_table="field_rep_v2",
        raw_table="campaign_fieldrep_raw",
        bronze_table="campaign_fieldrep",
        columns=[
            "field_rep_uuid",
            "id",
            "full_name",
            "phone_number",
            "brand_supplied_field_rep_id",
            "is_active",
            "state",
            "created_at",
            "updated_at",
        ],
        key_columns=["id"],
        watermark_field="updated_at",
    ),
    "campaign_campaignfieldrep": SourceTableSpec(
        source_table="campaign_field_rep_assignment_v2",
        raw_table="campaign_campaignfieldrep_raw",
        bronze_table="campaign_campaignfieldrep",
        columns=["campaign_field_rep_assignment_uuid", "id", "campaign_id", "field_rep_id", "campaign_uuid", "field_rep_uuid"],
        key_columns=["id"],
    ),
}
