from django.contrib import admin
from django.urls import include, path
from dashboard.views import (
    campaign_access_page,
    campaign_field_rep_collateral_insights,
    campaign_login,
    campaign_overview,
    campaign_performance_links_page,
    campaign_performance_page,
    campaign_state_list,
    etl_debug_page,
    field_rep_doctor_details,
    export_collateral_field_rep_insights,
    export_field_rep_insights,
    export_report,
    export_unmapped_doctors,
    menu_page,
    reports_home,
    send_access_email_view,
)
from dashboard.internal_data_admin import (
    internal_data_admin_bulk_delete,
    internal_data_admin_corrections,
    internal_data_admin_cleanup,
    internal_data_admin_delete,
    internal_data_admin_edit,
    internal_data_admin_home,
    internal_data_admin_login,
    internal_data_admin_logout,
    internal_data_admin_new,
    internal_data_admin_privacy,
    internal_data_admin_raw_dedupe,
    internal_data_admin_raw_download,
    internal_data_admin_raw_downloads,
    internal_data_admin_rfa_transfer_cleanup,
    internal_data_admin_transfer_cleanup,
    internal_data_admin_row,
    internal_data_admin_table,
)
from reporting.api_views import campaign_performance_api, campaign_performance_page_api, in_clinic_api, patient_education_api, red_flag_alert_api

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", reports_home, name="reports-home"),
    path("inclinic/", menu_page, name="menu"),
    path("reporting/api/red_flag_alert/", red_flag_alert_api, name="reporting-api-red-flag-alert"),
    path("reporting/api/in_clinic/", in_clinic_api, name="reporting-api-in-clinic"),
    path("reporting/api/patient_education/", patient_education_api, name="reporting-api-patient-education"),
    path("reporting/api/campaign-performance/", campaign_performance_api, name="reporting-api-campaign-performance"),
    path("reporting/api/campaign-performance/<str:campaign_id>/", campaign_performance_api, name="reporting-api-campaign-performance-specific"),
    path("reporting/api/campaign-performance-page/<str:campaign_id>/", campaign_performance_page_api, name="reporting-api-campaign-performance-page"),
    path("campaign-performance/links/", campaign_performance_links_page, name="campaign-performance-links"),
    path("campaign-performance/<str:campaign_id>/", campaign_performance_page, name="campaign-performance-page"),
    path("sapa-growth/", include("sapa_growth.urls")),
    path("pe-reports/", include("pe_reports.urls")),
    path("_internal/data-admin/login/", internal_data_admin_login, name="internal-data-admin-login"),
    path("_internal/data-admin/logout/", internal_data_admin_logout, name="internal-data-admin-logout"),
    path("_internal/data-admin/", internal_data_admin_home, name="internal-data-admin-home"),
    path("_internal/data-admin/raw-downloads/", internal_data_admin_raw_downloads, name="internal-data-admin-raw-downloads"),
    path("_internal/data-admin/raw-downloads/<str:schema>/<str:table>/download/", internal_data_admin_raw_download, name="internal-data-admin-raw-download"),
    path("_internal/data-admin/raw-dedupe/", internal_data_admin_raw_dedupe, name="internal-data-admin-raw-dedupe"),
    path("_internal/data-admin/transfer-cleanup/", internal_data_admin_transfer_cleanup, name="internal-data-admin-transfer-cleanup"),
    path("_internal/data-admin/rfa-transfer-cleanup/", internal_data_admin_rfa_transfer_cleanup, name="internal-data-admin-rfa-transfer-cleanup"),
    path("_internal/data-admin/corrections/", internal_data_admin_corrections, name="internal-data-admin-corrections"),
    path("_internal/data-admin/privacy/", internal_data_admin_privacy, name="internal-data-admin-privacy"),
    path("_internal/data-admin/cleanup/", internal_data_admin_cleanup, name="internal-data-admin-cleanup"),
    path("_internal/data-admin/<str:schema>/<str:table>/new/", internal_data_admin_new, name="internal-data-admin-new"),
    path("_internal/data-admin/<str:schema>/<str:table>/bulk-delete/", internal_data_admin_bulk_delete, name="internal-data-admin-bulk-delete"),
    path("_internal/data-admin/<str:schema>/<str:table>/row/", internal_data_admin_row, name="internal-data-admin-row"),
    path("_internal/data-admin/<str:schema>/<str:table>/row/edit/", internal_data_admin_edit, name="internal-data-admin-edit"),
    path("_internal/data-admin/<str:schema>/<str:table>/row/delete/", internal_data_admin_delete, name="internal-data-admin-delete"),
    path("_internal/data-admin/<str:schema>/<str:table>/", internal_data_admin_table, name="internal-data-admin-table"),
    path("debug/etl/", etl_debug_page, name="etl-debug"),
    path("campaign/<str:brand_campaign_id>/login/", campaign_login, name="campaign-login"),
    path("campaign/<str:brand_campaign_id>/access/", campaign_access_page, name="campaign-access"),
    path("campaign/<str:brand_campaign_id>/send-access-email/", send_access_email_view, name="campaign-send-access-email"),
    path("campaign/<str:brand_campaign_id>/performance/", campaign_performance_page, name="campaign-performance-page-legacy"),
    path("campaign/<str:brand_campaign_id>/states/", campaign_state_list, name="campaign-state-list"),
    path("campaign/<str:brand_campaign_id>/field-rep-insights/details/", field_rep_doctor_details, name="campaign-field-rep-insights-detail"),
    path("campaign/<str:brand_campaign_id>/export/", export_report, name="campaign-export"),
    path("campaign/<str:brand_campaign_id>/export/field-rep-insights/", export_field_rep_insights, name="campaign-field-rep-insights-export"),
    path("campaign/<str:brand_campaign_id>/export/unmapped-doctors/", export_unmapped_doctors, name="campaign-unmapped-doctors-export"),
    path(
        "campaign/<str:brand_campaign_id>/collateral/<str:collateral_id>/field-rep-insights/export/",
        export_collateral_field_rep_insights,
        name="campaign-field-rep-insights-collateral-export",
    ),
    path("campaign/<str:brand_campaign_id>/collateral/<str:collateral_id>/field-rep-insights/", campaign_field_rep_collateral_insights, name="campaign-field-rep-insights-collateral"),
    path("campaign/<str:brand_campaign_id>/", campaign_overview, name="campaign-overview-specific"),
]
